rvm:
 - 2.6
 - 2.7

script: 'bundle exec rspec spec'
gemfile:
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
  - gemfiles/6.1.gemfile

matrix:
  exclude:
  - rvm: 2.4
    gemfile: gemfiles/6.0.gemfile

# Move to containerized travis, see http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false
cache: bundler
